import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import { createServer, type Server } from 'node:http';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { getDownloadedFileKey } from './os-shared/package-file-utils';
import { OSRepoPackager } from './os-shared/repo-packager';
import { YumDownloader, YumMetadataParser } from './yum';
import type { OSPackageInfo, Repository } from './os-shared/types';

const repositoryBase: Omit<Repository, 'baseUrl'> = {
  id: 'yum-delivered-fixture',
  name: 'YUM delivered payload fixture',
  enabled: true,
  gpgCheck: false,
  isOfficial: false,
};

describe('YUM generated payload location is consumable by the real parser and downloader', () => {
  let server: Server | undefined;
  let tempDir: string | undefined;

  afterEach(async () => {
    if (server?.listening) {
      server.closeAllConnections();
      await new Promise<void>((resolve) => server?.close(() => resolve()));
    }
    server = undefined;
    if (tempDir) fs.rmSync(tempDir, { recursive: true, force: true });
    tempDir = undefined;
  });

  it('percent-encodes a raw basename once and downloads the generated bytes over loopback', async () => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'depssmuggler-yum-delivered-'));
    // Deliberately non-RPM bytes: this checks repository transport/path handling only.
    const payload = Buffer.from('fixture payload bytes, not an RPM');
    const rawFilename = 'literal space#&%20.rpm';
    const sourcePath = path.join(tempDir, rawFilename);
    fs.writeFileSync(sourcePath, payload);

    const pkg: OSPackageInfo = {
      name: 'model-package',
      version: '1.0',
      release: '1.el9',
      architecture: 'x86_64',
      size: 1,
      installedSize: 2,
      checksum: { type: 'sha256', value: '0'.repeat(64) },
      location: 'Packages/model-package-1.0-1.el9.x86_64.rpm',
      repository: { ...repositoryBase, baseUrl: 'http://placeholder.invalid' },
      dependencies: [],
      description: 'Loopback fixture',
    };
    const repoPath = path.join(tempDir, 'repo');
    await new OSRepoPackager().createLocalRepo(
      [pkg],
      new Map([[getDownloadedFileKey(pkg), sourcePath]]),
      { packageManager: 'yum', outputPath: repoPath, repoName: 'fixture-yum', includeSetupScript: false }
    );

    const copiedPayload = fs.readFileSync(path.join(repoPath, 'Packages', rawFilename));
    expect(copiedPayload).toEqual(payload);
    const repomdXml = fs.readFileSync(path.join(repoPath, 'repodata', 'repomd.xml'));
    const primaryXmlGz = fs.readFileSync(path.join(repoPath, 'repodata', 'primary.xml.gz'));
    const requestUrls: string[] = [];
    const fixtureServer = createServer((request, response) => {
      const requestUrl = request.url ?? '';
      requestUrls.push(requestUrl);
      if (requestUrl === '/repodata/repomd.xml') {
        response.writeHead(200, { 'content-type': 'application/xml' });
        response.end(repomdXml);
        return;
      }
      if (requestUrl === '/repodata/primary.xml.gz') {
        response.writeHead(200, { 'content-type': 'application/gzip' });
        response.end(primaryXmlGz);
        return;
      }

      let decodedPath: string;
      try {
        decodedPath = decodeURIComponent(new URL(requestUrl, 'http://127.0.0.1').pathname);
      } catch {
        response.writeHead(400);
        response.end('invalid path');
        return;
      }
      if (decodedPath === `/Packages/${rawFilename}`) {
        response.writeHead(200, {
          'content-type': 'application/octet-stream',
          'content-length': String(copiedPayload.length),
        });
        response.end(copiedPayload);
        return;
      }
      response.writeHead(404);
      response.end('not found');
    });
    server = fixtureServer;
    await new Promise<void>((resolve, reject) => {
      fixtureServer.once('error', reject);
      fixtureServer.listen(0, '127.0.0.1', () => resolve());
    });
    const address = fixtureServer.address();
    if (!address || typeof address === 'string') throw new Error('YUM loopback fixture did not start');

    const baseUrl = `http://127.0.0.1:${address.port}`;
    const repository: Repository = { ...repositoryBase, baseUrl };
    const metadataParser = new YumMetadataParser(repository, 'x86_64');
    const repomd = await metadataParser.parseRepomd();
    expect(repomd.primary).not.toBeNull();
    if (!repomd.primary) throw new Error('generated repomd is missing primary metadata');
    const primarySha256 = crypto.createHash('sha256').update(primaryXmlGz).digest('hex');
    expect(repomd.primary.location).toBe('repodata/primary.xml.gz');
    expect(repomd.primary.checksum.value).toBe(primarySha256);
    expect(Number(repomd.primary.size)).toBe(primaryXmlGz.length);
    const parsedByParser = await metadataParser.parsePrimary(repomd.primary.location);
    expect(parsedByParser).toHaveLength(1);
    const parsedPackage = parsedByParser[0];
    const encodedFilename = encodeURIComponent(rawFilename);
    expect(parsedPackage.location).toBe(`Packages/${encodedFilename}`);

    const downloadDir = path.join(tempDir, 'downloaded');
    const downloader = new YumDownloader({
      outputDir: downloadDir,
      distribution: {
        id: 'rocky-9',
        name: 'Rocky Linux 9',
        version: '9',
        packageManager: 'yum',
        architectures: ['x86_64'],
        defaultRepos: [],
        extendedRepos: [],
      },
      architecture: 'x86_64',
      repositories: [repository],
      concurrency: 1,
    });
    const result = await downloader.downloadPackage(parsedPackage);
    expect(result.success).toBe(true);
    expect(result.filePath).toBeDefined();
    if (!result.filePath) throw new Error('YUM downloader did not return a file path');

    const downloaded = fs.readFileSync(result.filePath);
    const expectedSha256 = crypto.createHash('sha256').update(payload).digest('hex');
    expect(downloaded).toEqual(payload);
    expect(crypto.createHash('sha256').update(downloaded).digest('hex')).toBe(expectedSha256);
    expect(requestUrls).toContain(`/Packages/${encodedFilename}`);
    expect(encodedFilename).toBe('literal%20space%23%26%2520.rpm');
    expect(requestUrls).not.toContain(`/Packages/${rawFilename}`);
  });
});
